M48
; DRILL file {KiCad (6.0.7-1)-1} date Thursday, 29 September 2022 at 15:21:57
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-29T15:21:57+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
%
G90
G05
T1
X4.8665Y-4.9935
X4.8665Y-5.0735
X5.0665Y-5.0335
T0
M30
